# Generated by Django 4.2.5 on 2023-10-05 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_to_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام ارسال کننده پیغام')),
                ('mozo', models.CharField(max_length=40, verbose_name='موضوع')),
                ('image', models.ImageField(upload_to='image', verbose_name='عکس')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_to_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام و نام خانوادگی ارسال کننده پیام')),
                ('mozo', models.CharField(max_length=80, verbose_name='موضوع')),
                ('image', models.ImageField(upload_to='image/', verbose_name='عکس')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار این پیام')),
                ('status', models.CharField(choices=[('p', 'ارسال شود'), ('d', 'ذخیره شود بعدا ارسال می کنم')], max_length=1, verbose_name='نوع وضغیت را انتخاب کنید')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to=settings.AUTH_USER_MODEL, verbose_name='...ارسال شود به ')),
            ],
        ),
        migrations.CreateModel(
            name='Arkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('semat', models.CharField(max_length=11, verbose_name='سمت')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arkan', to=settings.AUTH_USER_MODEL, verbose_name='ارکان')),
            ],
        ),
        migrations.CreateModel(
            name='Activety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arsefa', models.CharField(max_length=80, verbose_name='عرصه فعالیت')),
                ('tedadshe', models.CharField(max_length=80, verbose_name='تعداد شرکت کنندگان')),
                ('date', models.CharField(max_length=80, null=True, verbose_name='تاریخ')),
                ('numberhokm', models.CharField(max_length=20, verbose_name='شماره حکم')),
                ('name_masol', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی مسئول اردو')),
                ('phone_masol', models.CharField(max_length=11, verbose_name='شماره تلفن مسئول گروه')),
                ('message', models.CharField(max_length=500, verbose_name='شرح فعالیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Activety', to=settings.AUTH_USER_MODEL, verbose_name='گروه جهادی')),
            ],
        ),
    ]
